sudo: false
language: node_js
node_js: "20"
cache:
  directories:
    - "$HOME/.pnpm-store"
before_install:
  - npm install -g pnpm@10
install:
  - pnpm install --frozen-lockfile
script:
  - pnpm run build
  - pnpm run test
